### ISSUE TITLE
Remove GsContext from Seaside-GemStone-Core (SeasideSt/Seaside#1223), new Filetree (dalehenrich/filetree#195), port to 3.6.0

### ISSUE THREAD

**Issue by dalehenrich** [GsDevKit/GsDevKit_home#295]
GsDevKit/Grease has historically been used with GLASS1 (mainly because it takes time to do the conversion and some manual steps might be needed). I am having to modify some of the Seaside/GLASS code for 3.6.0 and it is likely that I will also have to make changes to dalehenrich/tode. So it seems that this is a good time to make the switch:
- [x] ~~change GLASS1 to use SeasideSt/Grease~~ instead of converting GLASS1 to use SeasideSt?Grease will just fix SeasideSt/Seaside#1223. See [this discussion for details](https://github.com/SeasideSt/Seaside/issues/1223#issuecomment-692869707)
   1. ~~SeasideSt/Grease#109~~
   2. ~~GsDevKit/GsDevKit#124~~
- [x] Drop Swazoo from Seaside - SeasideSt/Seaside#1222
- [x] Port Seaside to 3.6.0 - SeasideST/Seaside#1226
- [x] change GLASS1 to use branch issue_195 of dalehenrich/filetree#195. This is needed to properly support the use of SeasideSt/Grease, because SeasideSt/Grease no longer uses monticello meta data and GsDevKit/Grease has continued to use monticello metadata ...
- [x] fix GsDevKit/GsDevKit#126 ... 
   - [x] fix the bootstrap code in 3.6.0 first
   - [x] add fix to GLASS1
   - [x] explore potential to patch during GLASS1 load if not possible patch in 3.5.4 
- [x] port dalehenrich/tode to 3.6.0
   1. dalehenrich/tode#313
- [x] port GsDevKit/GsDevKit_upgrade to 3.6.0
- [x] port GsDevKit/GsDevKit_home to 3.6.0

**Comment by dalehenrich** [comment]
GsDevKit/gsApplicationTools#39 is not specifically related to 3.6.0, so we're good to go
